# This file is part of saunafs-monitoring.
# Copyright (C) 2025 Leil Storage OÜ
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
name: SaunaFS Monitoring
services:
    saunafs-monitoring:
        ports:
            - ${SAUNAFS_MONITORING_PORT:-8000}:${SAUNAFS_MONITORING_PORT:-8000}
        image: saunafs-monitoring:latest
        build: .
        environment:
            - SAUNAFS_MASTER_HOST=${SAUNAFS_MASTER_HOST:-sfsmaster}
            - SAUNAFS_MASTER_PORT=${SAUNAFS_MASTER_PORT:-9421}
            - SAUNAFS_MONITORING_HOST=${SAUNAFS_MONITORING_HOST:-0.0.0.0}
            - SAUNAFS_MONITORING_PORT=${SAUNAFS_MONITORING_PORT:-8000}
            - SAUNAFS_MONITORING_LOGLEVEL=${SAUNAFS_MONITORING_LOGLEVEL:-INFO}
    saunafs-api:
        ports:
            - ${SAUNAFS_API_PORT:-8001}:${SAUNAFS_API_PORT:-8001}
        image: saunafs-api:latest
        build:
            context: .
            dockerfile: Dockerfile.api
        environment:
            - SAUNAFS_MASTER_HOST=${SAUNAFS_MASTER_HOST:-sfsmaster}
            - SAUNAFS_MASTER_PORT=${SAUNAFS_MASTER_PORT:-9421}
            - SAUNAFS_API_HOST=${SAUNAFS_API_HOST:-0.0.0.0}
            - SAUNAFS_API_PORT=${SAUNAFS_API_PORT:-8001}
            - SAUNAFS_API_LOGLEVEL=${SAUNAFS_API_LOGLEVEL:-INFO}
