name: SaunaFS Monitoring
services:
    saunafs-monitoring:
        ports:
            - ${SAUNAFS_MONITORING_PORT:-8000}:${SAUNAFS_MONITORING_PORT:-8000}
        image: saunafs-monitoring:latest
        build: .
        environment:
            - SAUNAFS_MASTER_HOST=${SAUNAFS_MASTER_HOST:-sfsmaster}
            - SAUNAFS_MASTER_PORT=${SAUNAFS_MASTER_PORT:-9421}
            - SAUNAFS_MONITORING_HOST=${SAUNAFS_MONITORING_HOST:-0.0.0.0}
            - SAUNAFS_MONITORING_PORT=${SAUNAFS_MONITORING_PORT:-8000}
            - SAUNAFS_MONITORING_LOGLEVEL=${SAUNAFS_MONITORING_LOGLEVEL:-INFO}
    saunafs-api:
        ports:
            - ${SAUNAFS_API_PORT:-8001}:${SAUNAFS_API_PORT:-8001}
        image: saunafs-api:latest
        build:
            context: .
            dockerfile: Dockerfile.api
        environment:
            - SAUNAFS_MASTER_HOST=${SAUNAFS_MASTER_HOST:-sfsmaster}
            - SAUNAFS_MASTER_PORT=${SAUNAFS_MASTER_PORT:-9421}
            - SAUNAFS_API_HOST=${SAUNAFS_API_HOST:-0.0.0.0}
            - SAUNAFS_API_PORT=${SAUNAFS_API_PORT:-8001}
            - SAUNAFS_API_LOGLEVEL=${SAUNAFS_API_LOGLEVEL:-INFO}
