ARG PYTHON_VERSION=3.13
FROM ubuntu:24.04 AS base

ARG PYTHON_VERSION
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV PYTHON_VERSION=${PYTHON_VERSION}
ENV VIRTUAL_ENV=/opt/venv
ENV PATH=/opt/venv/bin:${PATH}

# Cache mounts only used in stages with apt operations to optimize build performance
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    set -e; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        software-properties-common; \
    add-apt-repository ppa:deadsnakes/ppa; \
    apt-get update

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    set -e; \
    apt-get install -y --no-install-recommends \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-venv \
    ; \
    python${PYTHON_VERSION} -m venv /opt/venv

FROM base AS builder-wheel
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV VIRTUAL_ENV=/opt/venv
ENV PATH=/opt/venv/bin:${PATH}
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    set -e; \
    apt-get install -y --no-install-recommends \
        build-essential \
    ; \
    python${PYTHON_VERSION} -m pip install --no-cache-dir \
        build \
        setuptools \
        tomli \
        wheel \
    ;

WORKDIR /workspace

COPY ./LICENSE ./LICENSE
COPY ./pyproject.toml ./pyproject.toml
COPY ./README.md ./README.md
COPY ./src ./src
COPY ./tests ./tests
RUN set -e; \
    mkdir -p /packages; \
    python${PYTHON_VERSION} -m build --wheel --outdir /tmp/wheels .; \
    cp /tmp/wheels/*.whl /packages/

FROM builder-wheel AS builder-deb

COPY ./utils/extract_pyproject.py ./utils/extract_pyproject.py
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    set -e; \
    apt-get install -y --no-install-recommends \
        ruby \
        ruby-dev \
    ; \
    gem install fpm; \
    # Install wheel with no dependencies for fpm
    pip install --prefix /tmp/install --no-cache-dir --no-deps /packages/*.whl; \
    ls -hAlF /tmp/install/lib/python${PYTHON_VERSION}; \
    PACKAGE_VERSION="$(python${PYTHON_VERSION} ./utils/extract_pyproject.py pyproject.toml project.version)"; \
    PACKAGE_NAME="$(python${PYTHON_VERSION} ./utils/extract_pyproject.py pyproject.toml project.name | tr '[:upper:]' '[:lower:]' | tr '_' '-')"; \
    DEPENDENCIES="$(python${PYTHON_VERSION} ./utils/extract_pyproject.py pyproject.toml project.dependencies)"; \
    fpm \
    --input-type dir \
    --output-type deb \
    --architecture all \
    ${DEPENDENCIES} \
    --name "${PACKAGE_NAME}" \
    --version "${PACKAGE_VERSION}-python${PYTHON_VERSION}" \
    --license "$(python${PYTHON_VERSION} ./utils/extract_pyproject.py pyproject.toml project.license)" \
    --maintainer "$(python${PYTHON_VERSION} ./utils/extract_pyproject.py pyproject.toml project.authors)" \
    --description "$(python${PYTHON_VERSION} ./utils/extract_pyproject.py pyproject.toml project.description)" \
    --url "$(python${PYTHON_VERSION} ./utils/extract_pyproject.py pyproject.toml project.urls.Homepage)" \
    --prefix / \
    /tmp/install/lib/python${PYTHON_VERSION}/site-packages/=/usr/lib/python3/dist-packages/; \
    mv *.deb /packages/

FROM scratch AS packages
COPY --from=builder-deb /packages/*.deb /
COPY --from=builder-wheel /packages/*.whl /

FROM base AS runtime-deb
COPY --from=builder-deb /packages /packages
WORKDIR /app
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    set -e; \
    dpkg -i /packages/*.deb || apt-get -y install -f; \
CMD ["/usr/bin/python3", "-m", "saunafs_monitoring.main"]

FROM python:${PYTHON_VERSION}-slim AS runtime
ARG PYTHON_VERSION
ENV PYTHON_VERSION=${PYTHON_VERSION}
COPY --from=builder-wheel /packages /packages
WORKDIR /app
RUN set -e; \
    python3 -m pip install /packages/*.whl
CMD ["/usr/local/bin/python3", "-m", "saunafs_monitoring.main"]
