[autoflake]
remove-all-unused-imports = true

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "leil-monitoring"
version = "1.0.0"
authors = [
    { name="LeilFS team", email="support@leil.io" },
]
description = "Monitoring web application for LeilFS"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-only" # Placeholder, not actual license
license-files = ["LICEN[CS]E*"]
dependencies = [
    "fastapi",
    "uvicorn",
    "jinja2",
    "httpx",
]

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "mypy"
]
test = [
    "pytest",
    "pytest-cov",
    "requests-mock",
]

[project.urls]
Homepage = "https://leil.io"

[tool.setuptools.packages.find]
where = ["src"]
include = ["leil_*"]

[tool.setuptools.package-data]
leil_monitoring = [
    "static/*",
    "templates/*",
]

[tool.jinja-lsp]
hide_undefined = false
templates = "./src/leil_monitoring/templates"
backend = ["./src"]
